research_task:
  description: >
    Search News about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024 and  current date is {date}.
  expected_output: >
    A list of news articles about {topic} with title,link,imageUrl and snippet.
  agent: researcher
reporting_task:
  description: >
    Review the context you got.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports of news articles.Make sure you have titles,links,thumbnail and summary for each news article.
    Formated as markdown with out '```'
  agent: reporting_analyst
